export enum ProductCategory {
  TORTA = 'TORTA',
  BANQUETERIA_DULCE = 'BANQUETERIA_DULCE',
  BANQUETERIA_SALADA = 'BANQUETERIA_SALADA',
  OTRO = 'OTRO',
}

export enum SaleStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_PREPARATION = 'IN_PREPARATION',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum EventType {
  CUMPLEANOS = 'CUMPLEANOS',
  MATRIMONIO = 'MATRIMONIO',
  BAUTIZO = 'BAUTIZO',
  EMPRESA = 'EMPRESA',
  OTRO = 'OTRO',
}

export enum EventStatus {
  QUOTED = 'QUOTED',
  CONFIRMED = 'CONFIRMED',
  IN_PREPARATION = 'IN_PREPARATION',
  EXECUTED = 'EXECUTED',
  INVOICED = 'INVOICED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  INVOICE = 'INVOICE',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT',
}